title: アサヒ株式会社 | 新サイトへリニューアルしました

defaults:
  - scope:
      path: ""
    values:
      layout: default

url: "https://asahi-jinz.github.io"
baseurl: "/asahi"

plugins:
  - jekyll-sitemap
